config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'foods#index'

  resources :foods, except: [:update]
  resources :recipes do
    member do
      patch 'toggle_public'
    end
    resources :recipe_foods
  end

  get 'shopping_list' => 'shopping_lists#index', as: :shopping_list

  get 'public_recipes', to: 'recipes#public_recipes', as: :public_recipes

  get 'up', to: 'rails/health#show', as: :rails_health_check
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_foods
  belongs_to :user

  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_user, only: %i[new create]
  before_action :set_recipe, only: %i[destroy show toggle_public]
  load_and_authorize_resource
  def index
    @recipes = current_user.recipes
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = @user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe created successfuy'
    else
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.recipe_foods.destroy_all
    if @recipe.destroy
      redirect_to recipes_path, notice: 'Recipe was successfully destroyed.'
    else
      redirect_to recipes_path, alert: 'Failed to destroy recipe.'
    end
  end

  def show
    @recipe_foods = @recipe.recipe_foods
  end

  def toggle_public
    @recipe.update(public: !@recipe.public)
    redirect_to @recipe, notice: 'Recipe updated successfully.'
  end

  def public_recipes
    @recipes = Recipe.where(public: true).order(id: :desc)
  end

  private

  def set_user
    @user = current_user
  end

  def set_recipe
    @recipe = Recipe.includes(:recipe_foods).find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/views/recipes/index.html.erb
<div class="col-md-8 mx-auto">
  <h2 class="mb-5" style="color: #fff; text-align: center;">List of Recipes</h2>
  <% @recipes.each do |recipe| %>
    <div class="border p-4 mb-2" style="background-color: #343A40; color: #fff;">
      <%= link_to recipe_path(recipe.id), class: 'remove_link' do %>
        <div class="d-flex mb-3">
          <h2 style="width: 150px; color: #17A2B8;"><%= recipe.name %></h2>
        <% end %>
        <p class="ms-5"><%= recipe.description %></p>
      </div>
      <%= button_to 'Remove', recipe_path(recipe.id), method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, class: 'btn btn-danger btn-sm' %>
    </div>
  <% end %>
  <div class="mb-3">
    <%= link_to "Add Recipe", new_recipe_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="col-md-6 d-flex align-items-center justify-content-center" style="background: linear-gradient(to right, #343A40, #1A1E21); color: #fff; height: 100vh; width: auto;">
  <div>
    <h2 class="text-center">Add New Recipe</h2>
    <hr class="border border-primary border-2 opacity-50">
    <%= form_with(model: @recipe, url: recipes_path, local: true) do |form| %>
      <div class="mb-3">
        <%= form.label :name, style: "display: block",class: "fw-bold form-label" %>
        <%= form.text_field :name, class: "form-control", placeholder: "Recipe Name" %>
      </div>
      <div class="mb-3">
        <%= form.label :preparation_time, style: "display: block",class: "fw-bold form-label" %>
        <%= form.text_field :preparation_time, class: "form-control", placeholder: "Preparation time" %>
      </div>
      <div class="mb-3">
        <%= form.label :cooking_time, style: "display: block",class: "fw-bold form-label" %>
        <%= form.text_field :cooking_time, class: "form-control", placeholder: "Cooking time" %>
      </div>
      <div class="mb-3">
        <%= form.label :description, style: "display: block",class: "fw-bold form-label" %>
        <%= form.text_area :description, class: "form-control", placeholder: "Description" %>
      </div>
      <div class="mb-3">
        <%= form.label :public, class: "fw-bold form-label me-3" %>
        <%= form.check_box :public, class: "form-check-input" %>
      </div>
      <div class="mb-3">
        <%= form.submit "Create Recipe", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/public_recipes.html.erb
<div class="col-md-6 mx-auto" style="width: 80%;">
  <hr class="border-light mb-4">
  <% @recipes.each do |recipe| %>
    <div class="bg-dark text-light border rounded p-4 mb-3" style="background: linear-gradient(to right, #343A40, #343A40);">
      <%= link_to recipe_path(recipe.id), class: 'text-light text-decoration-none' do %>
        <h2 class="mb-3"><%= recipe.name %></h2>
      <% end %>
      <h4 class="mb-3">by: <%= recipe.user.name %></h4>
      <% if can? :destroy, recipe %>
        <% if current_user && current_user == recipe.user %>
          <%= button_to 'Remove Recipe', recipe_path(recipe.id), method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, class: 'btn btn-danger btn-sm mb-3' %>
        <% end %>
      <% end %>
      <div class="px-4">
        <p class="mb-2">Total Food Items: <%= recipe.recipe_foods.length %></p>
        <p>Total Price: $<%= recipe.recipe_foods.sum { |recipe_food| recipe_food.food.price * recipe_food.quantity } %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="container d-flex justify-content-center">
  <div class="col-md-8 text-center" style="background: linear-gradient(to right, #343a40, #1a1e21); color: #fff; padding: 20px; border-radius: 10px; height: 100vh; width: 100vh;margin-top: 45px;">

    <h1><%= @recipe.name %></h1>

    <%= form_with(model: @recipe, url: toggle_public_recipe_path(@recipe), method: :patch) do |form| %>
      <% if current_user == @recipe.user %>
        <%= form.button @recipe.public ? 'Private' : 'Public', class: 'btn btn-primary btn-sm float-end' %>
      <% end %>
    <% end %>

    <p><strong>Preparation Time:</strong> <%= @recipe.preparation_time %> <%= "hour".pluralize(@recipe.preparation_time) %></p>
    <p><strong>Cooking Time:</strong> <%= @recipe.cooking_time  %> <%= "hour".pluralize(@recipe.cooking_time) %></p>
    <p><strong>State of Public:</strong> <%= @recipe.public %></p>
    <p><%= @recipe.description %></p>

    <% if current_user == @recipe.user %>
      <%= link_to 'Generate Shopping List', shopping_list_path, class: 'btn btn-success' %>
      <%= link_to 'Add Ingredient', new_recipe_recipe_food_path(@recipe.id), class: 'btn btn-info float-end' %>
    <% end %>

    <hr class="border border-success border-2 opacity-50">
    <table class="table table-striped table-dark">
      <thead>
        <tr>
          <th scope="col">Food</th>
          <th scope="col">Quantity</th>
          <th scope="col">Value</th>
          <th scope="col" class="text-center">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @recipe_foods.each do |recipe_food| %>
          <tr>
            <td><%= recipe_food.food.name %></td>
            <td><%= recipe_food.quantity %> </td>
            <td>$ <%= recipe_food.quantity * recipe_food.food.price %> </td>
            <td class="text-center">
              <%= button_to 'Remove', recipe_recipe_food_path(@recipe, recipe_food), method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, class: 'btn btn-danger btn-sm float-start' %>
              <%= link_to 'Modify', edit_recipe_recipe_food_path(@recipe, recipe_food), class: 'btn btn-info btn-sm' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>