config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'foods#index'

  resources :foods, except: [:update]
  resources :recipes do
    member do
      patch 'toggle_public'
    end
    resources :recipe_foods
  end

  get 'shopping_list' => 'shopping_lists#index', as: :shopping_list

  get 'public_recipes', to: 'recipes#public_recipes', as: :public_recipes

  get 'up', to: 'rails/health#show', as: :rails_health_check
end

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background: linear-gradient(to right, #861fa9, #acaed4); padding: 20px;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#" style="color: #ffffff; font-size: 24px; margin-right: 50px;">Recipe App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">

      <% if current_user %>

      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Foods List", foods_path, type: "button", class: "btn btn-success btn-sm me-2 nav-transition" %>
        </li>
        <li class="nav-item">
          <%= link_to "Recipes List", recipes_path, type: "button", class: "btn btn-warning btn-sm me-2 nav-transition" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Public Recipes List", public_recipes_path, class: "btn btn-info btn-sm me-2 nav-transition" %>
        </li>
        <li class="nav-item">
         
            <%= link_to 'Generate Shopping List', shopping_list_path,  class: "btn btn-info btn-sm me-2 nav-transition" %>
          
        </li>
      </ul>
      
      <% else %>

      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link text-light" href="#" style="transition: color 0.3s ease; font-size: 18px;">Public Recipes</a>
        </li>
      </ul>

      <% end %>

      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item"><%= link_to "Edit Your Account", edit_user_registration_path,class: "btn btn-danger btn-sm nav-transition-blue" %></li>
          <li class="nav-item"><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger btn-sm nav-transition-blue" %></li>
        <% else %>
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-info btn-sm me-2 nav-transition" %></li>
          <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class: "btn btn-success btn-sm me-2 nav-transition" %></li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

<style>
  .nav-transition {
    transition: background-color 0.3s ease, color 0.3s ease;
    background-color: #4e54c8;
    color: #ffffff;
  }

  .nav-transition:hover {
    background-color: green;
  }

  .nav-transition-blue {
    background-color: blue;
  }

  .nav-transition-blue:hover {
    background-color: #0066cc;
  }
</style>