config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'foods#index'

  resources :foods, except: [:update]
  resources :recipes do
    member do
      patch 'toggle_public'
    end
    resources :recipe_foods
  end

  get 'shopping_list' => 'shopping_lists#index', as: :shopping_list

  get 'public_recipes', to: 'recipes#public_recipes', as: :public_recipes

  get 'up', to: 'rails/health#show', as: :rails_health_check
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods
  belongs_to :user

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    # "has_many :foods" because of this is in model hence there is" current_user.foods"
    @foods = current_user.foods
  end

  def new
    @food = Food.new
    @user = current_user
  end

  def create
    # creating a new Food object associated with the current_user without saving it to the database immediately.
    @food = current_user.foods.build(food_params)
    if @food.save
      redirect_to foods_path, notice: 'New Food created successfully'
    else
      render :new
    end
  end

  def destroy
    # when u access /foods/1, the 1 is the :id parameter.
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path, notice: 'Your Food is Deleted successfully'
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<style>
  .btn-dark-blue {
    background: lightcoral;
  }

  .btn-dark-blue:hover {
    background: linear-gradient(to right, #003366, #001f3f);
    color: #ffffff;
  }

  .table-all, .table-all-params {
    display: flex;
    justify-content: space-between;
    padding: 10px;
    border: 1px solid #001f3f;
    margin-bottom: 5px;
  }

  .table-all {
    background: linear-gradient(to right, #001f3f, #003366);
    color: #ffffff;
  }

  .table-all-params {
    background-color: #4484c4;
    color: #ffffff;
  }
</style>

<div class="container mt-5">
  <%= link_to 'Add New Food', new_food_path, class: "btn btn-dark-blue mb-3" %>
  
  <div>
    <% if @foods.any? %>
      <div class="table-responsive">
        <div class="table-all">
          <p>Food Name</p>
          <p>Measurement Unit</p>
          <p>Unit Price</p>
          <p>Quantity</p>
          <p>Action</p>
        </div>

        <% @foods.each do |food| %>
          <div class="table-all-params">
            <p><%= food.name %></p>
            <p><%= food.measurement_unit %></p>
            <p>$ <%= food.price %> </p>
            <p><%= food.quantity %></p>
            <%= button_to 'Delete Food', food_path(food.id), method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="text-center">
        <h3>Click on Add new food to add foods here</h3>
      </div>
    <% end %>
  </div>
</div>

app/views/foods/new.html.erb
<div class="container-fluid bg-dark text-light" style="height: 100vh; display: flex; align-items: center; justify-content: center;">
  <%= form_with(model: @food, url: foods_path, local: true, class: "needs-validation", novalidate: true) do |form| %>

    <div class="mb-3">
      <%= form.label :name, class: "form-label text-light" %>
      <%= form.text_field :name, class: "form-control", placeholder: "Enter Food Name", required: true %>
      <div class="invalid-feedback">Please enter a valid food name.</div>
    </div>

    <div class="mb-3">
      <%= form.label :measurement_unit, class: "form-label text-light" %>
      <%= form.text_field :measurement_unit, class: "form-control", placeholder: "Enter Measurement Unit", required: true %>
      <div class="invalid-feedback">Please enter a valid measurement unit.</div>
    </div>

    <div class="mb-3">
      <%= form.label :price, class: "form-label text-light" %>
      <%= form.text_field :price, class: "form-control", placeholder: "Enter Food Price", required: true %>
      <div class="invalid-feedback">Please enter a valid food price.</div>
    </div>

    <div class="mb-3">
      <%= form.label :quantity, class: "form-label text-light" %>
      <%= form.text_field :quantity, class: "form-control", placeholder: "Enter Food Quantity", required: true %>
      <div class="invalid-feedback">Please enter a valid food quantity.</div>
    </div>

    <div class="mb-3">
      <%= form.submit "Create New Food", class: "btn btn-primary" %>
    </div>

  <% end %>
</div>