config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'foods#index'

  resources :foods, except: [:update]
  resources :recipes do
    member do
      patch 'toggle_public'
    end
    resources :recipe_foods
  end

  get 'shopping_list' => 'shopping_lists#index', as: :shopping_list

  get 'public_recipes', to: 'recipes#public_recipes', as: :public_recipes

  get 'up', to: 'rails/health#show', as: :rails_health_check
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :find_recipe_food, only: %i[destroy edit update]

  def new
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe_id = params[:recipe_id]

    if @recipe_food.save
      redirect_to recipe_path(params[:recipe_id]), notice: 'Food ingredient was successfully added.'
    else
      render :new
    end
  end

  def destroy
    @recipe_food.destroy
    redirect_to recipe_path(params[:recipe_id]), notice: 'Food ingredient was successfully eliminated.'
  end

  def edit; end

  def update
    if @recipe_food.update(recipe_food_params)
      redirect_to recipe_path(params[:recipe_id]), notice: 'Food ingredient was successfully updated.'
    else
      render :edit
    end
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end

  def find_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end
end

app/views/recipe_foods/edit.html.erb
<div class="col-md-6">
  <h2>Edit Ingredient</h2>
  <hr class="border border-primary border-2 opacity-50">
  <%= form_with(model: @recipe_food, method: :patch, url: recipe_recipe_food_path, local: true) do |form| %>
  
    <div class="mb-3">
      <%= form.label :quantity, style: "display: block",class: "fw-bold form-label" %>
      <%= form.number_field :quantity, class: "form-control" %>
    </div>
  
    <div class="mb-3">
      <%= form.label :food_id, style: "display: block",class: "fw-bold form-label" %>
       <%= form.collection_select :food_id, current_user.foods, :id, :name, { include_blank: false }, class: 'form-control' %>
    </div>
  
     <div class="mb-3">
      <%= form.submit "Update", class: 'btn btn-primary' %>
    </div>
  
  <% end %>
  </div>

app/views/recipe_foods/new.html.erb
<div class="col-md-6 text-center" style="background: linear-gradient(to right, #343A40, #343A40); color: #fff; padding: 20px; border-radius: 10px; width: 100vw; height: 100vh;">

  <h2 class="mb-4">Add Ingredient</h2>
  <hr class="border border-primary border-2 opacity-50">
  
  <%= form_with(model: @recipe_food, url: recipe_recipe_foods_path, local: true) do |form| %>
    <div class="mb-3">
      <%= form.label :quantity, style: "display: block", class: "fw-bold form-label text-light" %>
      <%= form.number_field :quantity, class: "form-control form-control-sm" %>
    </div>
  
    <div class="mb-3">
      <%= form.label :food_id, style: "display: block", class: "fw-bold form-label text-light" %>
      <%= form.collection_select :food_id, current_user.foods, :id, :name, { include_blank: false }, class: 'form-control form-control-sm' %>
    </div>
  
    <div class="mb-3">
      <%= form.submit "Create Ingredient", class: 'btn btn-success' %>
    </div>
  <% end %>

</div>